source "https://rubygems.org"
gem 'selenium-cucumber', '~> 3.1', '>= 3.1.5'
gem "axe-devtools-selenium", '~> 4.9.0', :source => 'https://agora.dequecloud.com/artifactory/api/gems/devtools-gems'
gem "axe-devtools-cucumber", '~> 4.9.0', :source => 'https://agora.dequecloud.com/artifactory/api/gems/devtools-gems'
gem 'webdrivers', '~> 5.0'